from selenium import webdriver
from selenium.webdriver.common.by import By
import time

def mostrar_datos(dueMinimo):
    driver = webdriver.Chrome()

    try:
        driver.get("https://the-internet.herokuapp.com")
        driver.maximize_window()
        link_dataTables = driver.find_element(By.CSS_SELECTOR, '#content > ul > li:nth-child(41) > a')
        link_dataTables.click()
        dueValue1 = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(1) > td:nth-child(4)')
        dueValue2 = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(2) > td:nth-child(4)')
        dueValue3 = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(3) > td:nth-child(4)')
        dueValue4 = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(4) > td:nth-child(4)')
        if float(dueValue1.text[1:]) > dueMinimo:
            time.sleep(3)
            lastName = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(1) > td:nth-child(1)')
            firstName = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(1) > td:nth-child(2)')
            email = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(1) > td:nth-child(3)')
            webSite = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(1) > td:nth-child(5)')
            print("First Name: ", firstName.text)
            print("Last Name: ", lastName.text)
            print("Email: ", email.text)
            print("Due: ", dueValue1.text)
            print("Web site: ", webSite.text)
            print("--------")
        if float(dueValue2.text[1:]) > dueMinimo:
            time.sleep(3)
            lastName = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(2) > td:nth-child(1)')
            firstName = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(2) > td:nth-child(2)')
            email = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(2) > td:nth-child(3)')
            webSite = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(2) > td:nth-child(5)')
            print("First Name: ", firstName.text)
            print("Last Name: ", lastName.text)
            print("Email: ", email.text)
            print("Due: ", dueValue2.text)
            print("Web site: ", webSite.text)
            print("--------")
        if float(dueValue3.text[1:]) > dueMinimo:
            time.sleep(3)
            lastName = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(3) > td:nth-child(1)')
            firstName = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(3) > td:nth-child(2)')
            email = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(3) > td:nth-child(3)')
            webSite = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(3) > td:nth-child(5)')
            print("First Name: ", firstName.text)
            print("Last Name: ", lastName.text)
            print("Email: ", email.text)
            print("Due: ", dueValue3.text)
            print("Web site: ", webSite.text)
            print("--------")
        if float(dueValue4.text[1:]) > dueMinimo:
            time.sleep(3)
            lastName = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(4) > td:nth-child(1)')
            firstName = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(4) > td:nth-child(2)')
            email = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(4) > td:nth-child(3)')
            webSite = driver.find_element(By.CSS_SELECTOR, '#table1 > tbody > tr:nth-child(4) > td:nth-child(5)')
            print("First Name: ", firstName.text)
            print("Last Name: ", lastName.text)
            print("Email: ", email.text)
            print("Due: ", dueValue4.text)
            print("Web site: ", webSite.text)
            print("--------")
    finally:
        driver.quit()


print("DUE > 49")
print("--------")
mostrar_datos(49)
print("--------")
print("DUE > 50")
print("--------")
mostrar_datos(50)
print("--------")
print("DUE > 99")
print("--------")
mostrar_datos(99)
print("--------")
print("DUE > 100")
print("--------")
mostrar_datos(100)
print("--------")